build:
    os: linux
    arch: x86
    sign_key: private_key.pem
    sign_certificate: sp-client.pem
    remove_non_regular_files: True

publish:
    url: staging-fusion.westeurope.cloudapp.azure.com
    service_uid: ade784fb-bc88-4071-9d22-7d8d39563c91
    tls_key: private_key.pem
    tls_certificate: sp-client.pem
    version: "1.1"

configuration:
    state:
        filename: state.dat
        required: False

    cmd: python3 vis_client_example.py
    hostname: 'service-hello-world.local'
    workingDir: '/'
    env:
        - WEBHOOK_SITE=https://webhook.site/e81827db-1c65-457b-9648-c6469c0edbd1
